name: Deploy EKS Cluster

on:
  push:
    branches:
      - main

jobs:
  create-eks-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Change this if using another AWS region

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Install kubectl
        run: |
          curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/2023-09-28/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Create EKS Cluster
        run: |
          eksctl create cluster \
            --name my-cluster \
            --region us-west-2 \
            --nodegroup-name my-node-group \
            --node-type t3.medium \
            --nodes 2

      - name: Verify Cluster
        run: |
          aws eks --region us-west-2 update-kubeconfig --name my-cluster
          kubectl get nodes

      - name: Post Configure AWS Credentials
        run: |
          echo "EKS Cluster deployment completed successfully!"
