name: Deploy EKS Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Create EKS Cluster
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Create EKS Cluster
        run: |
          eksctl create cluster --name my-eks-cluster --region us-west-2 \
          --nodegroup-name standard-workers --node-type t3.medium --nodes 2 \
          --nodes-min 1 --nodes-max 3 --managed

      - name: Verify Cluster
        run: |
          aws eks --region us-west-2 update-kubeconfig --name my-eks-cluster
          kubectl get nodes
