name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Check if EKS Cluster Exists
        run: |
          if eksctl get cluster --name my-cluster --region ap-south-1; then
            echo "Cluster already exists, skipping creation."
            exit 0
          fi

      - name: Create EKS Cluster (if not exists)
        run: eksctl create cluster --name my-cluster --region ap-south-1

      - name: Update Kubeconfig
        run: aws eks --region ap-south-1 update-kubeconfig --name my-cluster

      - name: Deploy Application
        run: kubectl apply -f k8s/

      - name: Verify Deployment
        run: kubectl get pods -o wide
